### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by ChrispaixK** [Ibizugbe/car-valley-backend#16]
> Project link [here](https://github.com/users/Ibizugbe/projects/2/views/1)
> Our collaboration consists of 4 members split into two main groups :
 * Front end 
   * @benshidanny11 
   * @ChrispaixK 
 * Back-end
   * @Ibizugbe 
   * @rex-9  

### Points Per Coder

**@rex-9** - 2+1+2+2 = **7**pts
**@Ibizugbe** - 2+3+2 = **7**pts
**@ChrispaixK** - 1+2+4 = **7**pts
**@benshidanny11** - 2+4+1 = **7**pts

attached below is a picture of the kanban board.
![image](https://user-images.githubusercontent.com/64643995/203681779-db68ea88-270c-49e0-a1f9-09347164fabf.png)

**Comment by Meltrust** [comment]
Hi @ChrispaixK,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Nice issue layout✔️ 
- All tasks have points✔️ 
- Pointing is fear✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
